### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by andreclaudino** [concurrentes-fiuba/actix-async-handler#7]
Great project, but would be better if there were some examples on how to use. I got confused about where does the macro goes (function or handler implementation) and that means opening the code to understand. Would be easier if the examples were on README.

**Comment by arielscarpinelli** [comment]
Would you care for writing some docs and submitting a PR ?

**Comment by arielscarpinelli** [comment]
Added some examples and known limitations. Feel free to send a PR to extend.
